# Cloudflare Pages Static Site Configuration
# Ensures proper static HTML file serving

[build]
command = "npm run build"
publish = "."

[build.environment]
NODE_VERSION = "18"

# Static site configuration
compatibility_date = "2025-09-12"
name = "badgertechnologies"

# No Workers or Functions - pure static site
# Serve HTML files directly from root directory