name = "badgertechnologies"
main = "src/worker.js"
compatibility_date = "2023-10-30"
pages_build_output_dir = "dist"

[vars]
CONTACT_EMAIL = "info@badgertechnologies.us"
SITE_NAME = "Badger Technologies"

[observability]
enabled = true

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[assets]
# Serve from the staged build output directory
directory = "dist"
# Bind the assets namespace to env.ASSETS in the Worker
binding = "ASSETS"

[build]
command = "npm run build"